const DEFAULT_BIND_WHITELIST = [
  'AF',
  'AM',
  'CW',
  'AO',
  'AX',
  'BD',
  'BF',
  'BG',
  'BI',
  'BL',
  'BO',
  'CA',
  'CC',
  'CF',
  'CM',
  'CX',
  'DZ',
  'EC',
  'EG',
  'EH',
  'ET',
  'FK',
  'FR',
  'GH',
  'GN',
  'GW',
  'HN',
  'HT',
  'ID',
  'IO',
  'JM',
  'JO',
  'JP',
  'KG',
  'KH',
  'KM',
  'KR',
  'LB',
  'LK',
  'LY',
  'ME',
  'MF',
  'MG',
  'ML',
  'MN',
  'MP',
  'MU',
  'MY',
  'MZ',
  'NG',
  'NU',
  'PE',
  'PK',
  'PN',
  'PS',
  'SA',
  'SD',
  'SH',
  'SI',
  'SJ',
  'SL',
  'SM',
  'SN',
  'TG',
  'TH',
  'TJ',
  'TK',
  'TL',
  'TM',
  'TW',
  'UG',
  'UM',
  'US',
  'UZ',
  'VA',
  'VN',
  'VU',
  'RS',
  'ZM',
  'ZW',
];

const DEFAULT_RECOMMENDED_WHITELIST = [
  'ID',
  'PH',
  'CO',
  'UA',
  'NL',
  'BR',
  'PL',
  'GB',
  'CA',
  'MX',
  'IL',
  'FR',
  'SE',
  'TH',
  'HK',
];

module.exports = {
  serviceKey: 'openai_chatgpt',
  displayName: 'OPENAI (ChatGPT)',
  bindWhitelistIso2: DEFAULT_BIND_WHITELIST,
  recommendedWhitelistIso2: DEFAULT_RECOMMENDED_WHITELIST,
  providerMappings: [
    {
      providerKey: 'hero-sms',
      displayName: 'Hero SMS',
      serviceCode: process.env.HERO_SMS_SERVICE_CODE || 'dr',
      baseUrl: 'https://hero-sms.com/stubs/handler_api.php',
      keyEnv: 'HERO_SMS_API_KEY',
    },
    {
      providerKey: 'smsbower',
      displayName: 'SMSBower',
      serviceCode: process.env.SMSBOWER_SERVICE_CODE || 'dr',
      baseUrl: 'https://smsbower.page/stubs/handler_api.php',
      publicPricesUrl: 'https://smsbower.app/activations/getPricesByService',
      keyEnv: 'SMSBOWER_API_KEY',
    },
    {
      providerKey: '5sim',
      displayName: '5SIM',
      serviceCode: process.env.FIVESIM_SERVICE_CODE || 'openai',
      baseUrl: 'https://5sim.net/v1',
      keyEnv: 'FIVESIM_API_KEY',
    },
    {
      providerKey: 'nexsms',
      displayName: 'NexSMS',
      serviceCode: process.env.NEXSMS_SERVICE_CODE || 'dr',
      baseUrl: 'https://api.nexsms.net/api',
      keyEnv: 'NEXSMS_API_KEY',
    },
    {
      providerKey: 'grizzlysms',
      displayName: 'Grizzly SMS',
      serviceCode: process.env.GRIZZLYSMS_SERVICE_CODE || 'dr',
      baseUrl: 'https://api.grizzlysms.com/stubs/handler_api.php',
      keyEnv: 'GRIZZLYSMS_API_KEY',
    },
    {
      providerKey: 'sms-verification-number',
      displayName: 'SMS Verification Number',
      serviceCode: process.env.SMS_VERIFICATION_SERVICE_CODE || 'dr',
      baseUrl: 'https://sms-verification-number.com/stubs/handler_api',
      keyEnv: 'SMS_VERIFICATION_API_KEY',
    },
    {
      providerKey: 'smspool',
      displayName: 'SMSPool',
      serviceCode: process.env.SMSPOOL_SERVICE_CODE || 'dr',
      baseUrl: 'https://api.smspool.net/stubs/handler_api',
      keyEnv: 'SMSPOOL_API_KEY',
    },
  ],
};
